// <auto-generated />
using InventorySystemDay1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventorySystemDay1.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InventorySystemDay1.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Discontinued = true,
                            Name = "Chopping Board",
                            Quantity = 3
                        },
                        new
                        {
                            ID = -2,
                            Discontinued = false,
                            Name = "Knife",
                            Quantity = 20
                        },
                        new
                        {
                            ID = -3,
                            Discontinued = false,
                            Name = "Bowl",
                            Quantity = 100
                        },
                        new
                        {
                            ID = -4,
                            Discontinued = false,
                            Name = "Plates",
                            Quantity = 3
                        },
                        new
                        {
                            ID = -5,
                            Discontinued = false,
                            Name = "IPhone",
                            Quantity = 200
                        },
                        new
                        {
                            ID = -6,
                            Discontinued = false,
                            Name = "IPad",
                            Quantity = 500
                        },
                        new
                        {
                            ID = -7,
                            Discontinued = false,
                            Name = "Heater",
                            Quantity = 50
                        },
                        new
                        {
                            ID = -8,
                            Discontinued = false,
                            Name = "Fan",
                            Quantity = 200
                        },
                        new
                        {
                            ID = -9,
                            Discontinued = false,
                            Name = "Water Bottle",
                            Quantity = 200
                        },
                        new
                        {
                            ID = -10,
                            Discontinued = false,
                            Name = "Chair",
                            Quantity = 200
                        },
                        new
                        {
                            ID = -11,
                            Discontinued = true,
                            Name = "Pen",
                            Quantity = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
